"""Create initial tables

Revision ID: 9582c074a083
Revises: 
Create Date: 2025-03-13 18:50:24.570260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9582c074a083'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('conversation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_user_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['registration_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('naps_registration_code', sa.String(length=11), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'TRANSGENDER', name='gender'), nullable=False),
    sa.Column('disability_divyang', sa.Enum('YES', 'NO', name='yesno'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('parent_name', sa.String(), nullable=False),
    sa.Column('parent_relation', sa.Enum('FATHER', 'MOTHER', 'SPOUSE', name='parentrelation'), nullable=False),
    sa.Column('religion', sa.Enum('HINDU', 'MUSLIM', 'CHRISTIAN', 'SIKH', 'BUDDHIST', 'JAIN', 'OTHERS', name='religion'), nullable=False),
    sa.Column('category', sa.Enum('GENERAL', 'OBC', 'SC', 'ST', name='category'), nullable=False),
    sa.Column('qualification_type', sa.Enum('EDUCATIONAL', 'SCHEME', name='qualificationtype'), nullable=False),
    sa.Column('education_trade', sa.Enum('FIFTH', 'SIXTH', 'SEVENTH', 'EIGHTH', 'NINTH', 'TENTH', 'ELEVENTH', 'TWELFTH', 'ITI', 'MSBSVET', 'ITI_DUAL', 'ITI_RESULT_AWAITED', 'DIPLOMA_PURSUING', 'GRADUATE_PURSUING', 'ADVANCED_DIPLOMA', 'GRADUATE', 'POST_GRADUATE', 'DOCTORAL', 'OTHERS', name='educationtrade'), nullable=True),
    sa.Column('scheme_trade', sa.Enum('NULM', 'DDUGKY', 'STATE_SPECIFIC', 'PMKVY', 'SDI_MES', 'CENTRAL', 'VSE_MHRD', 'PMKVY_MSDE', 'DDUGKY_MORD', 'ESTP_NULM', 'PMAYG_MOSJE', 'CPWD_MOUD', 'NSKFDC_MOSJE', 'NBCFDC_MOSJE', 'NSDFDC_MOSJE', 'ISDS_TEXTILES', 'SEEKHO_MAMA', 'SSC_FEE', name='schemetrade'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['registration_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('naps_registration_code'),
    sa.UniqueConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_registrations')
    op.drop_table('conversation_messages')
    op.drop_table('registration_sessions')
    # ### end Alembic commands ###
